// <auto-generated />
using System;
using ContactManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Married")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = true,
                            Name = "John Doe",
                            Phone = "555-1234",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1985, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = false,
                            Name = "Jane Smith",
                            Phone = "555-5678",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1975, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = true,
                            Name = "Mark Johnson",
                            Phone = "555-9876",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1992, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = false,
                            Name = "Emily Brown",
                            Phone = "555-4321",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1988, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = true,
                            Name = "Michael Wilson",
                            Phone = "555-8765",
                            Salary = 55000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
